trainings:
    resource: "@HrisTrainingBundle/Controller/TrainingController.php"
    type: annotation

trainingevent:
    resource: "@HrisTrainingBundle/Controller/TraininginstanceController.php"
    type: annotation

sponsors:
    resource: "@HrisTrainingBundle/Controller/SponsorController.php"
    type: annotation

venues:
    resource: "@HrisTrainingBundle/Controller/VenueController.php"
    type: annotation

trainers:
    resource: "@HrisTrainingBundle/Controller/TrainersController.php"
    type: annotation

participants:
    resource: "@HrisTrainingBundle/Controller/ParticipantController.php"
    type: annotation

trainingreports:
    resource: "@HrisTrainingBundle/Controller/TrainingReportController.php"
    type: annotation

facilitator:
    resource: "@HrisTrainingBundle/Controller/FacilitatorController.php"
    type: annotation

instanceRecords:
    resource: "@HrisTrainingBundle/Controller/instanceRecordController.php"
    type: annotation

#historytrainingreport:
#    resource: "@HrisReportsBundle/Controller/ReportHistoryTrainingController.php"
#    type: annotation
#
#organisationunitByLevels:
#    resource: "@HrisReportsBundle/Controller/ReportOrganisationunitByLevelsController.php"
#    type: annotation
#
#organisationunitByGroupset:
#    resource: "@HrisReportsBundle/Controller/ReportOrganisationunitByGroupsetController.php"
#    type: annotation
#
#organisationunitCompleteness:
#    resource: "@HrisReportsBundle/Controller/ReportOrganisationunitCompletenessController.php"
#    type: annotation
#
#recordsReport:
#    resource: "@HrisReportsBundle/Controller/ReportEmployeeRecordsController.php"
#    type: annotation
#
#friendlyReport:
#    resource: "@HrisReportsBundle/Controller/ReportFriendlyReportController.php"
#    type: annotation
#
