parameters:
#    hris_nursing.example.class: Hris\NursingBundle\Example

services:
    hris_nursing.configure_menu_listener:
            class: Hris\NursingBundle\EventListener\ConfigureMenuListener
            tags:
                - { name: kernel.event_listener, event: hris_nursing.menu_configure, method: onMenuConfigure }

